name: encrypt_pc
version: 1.0.0-rc
description: A set of high-level APIs over pointycastle (https://github.com/bcgit/pc-dart) for two-way cryptography. A fork of encrypt (https://github.com/leocavalcante/encrypt).
repository: https://github.com/SmebdyNbdy/encrypt-pc

executables:
  secure-random:

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.3.1
  asn1lib: ^1.5.0
  clock: ^1.1.1
  collection: ^1.17.0
  crypto: ^3.0.2
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

false_secrets:
 - /test/*.pem
